# Generated by Django 5.0.6 on 2024-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETFData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('asset_class', models.CharField(max_length=255)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notional_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cusip', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=100)),
                ('sedol', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
