# Generated by Django 5.0.6 on 2024-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETF_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_shortname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.AddField(
            model_name='etf_holdings',
            name='firm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etf_holdings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etf_name', models.CharField(max_length=100)),
                ('etf_shortname', models.CharField(max_length=30)),
                ('etf_link', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stocks', models.ManyToManyField(to='ETF_services.stock')),
            ],
            options={
                'db_table': 'ETF',
            },
        ),
    ]
