# Generated by Django 5.0.6 on 2024-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETF_services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailabilityDate',
        ),
        migrations.AddField(
            model_name='etf',
            name='etf_stocks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etf',
            name='stocks',
            field=models.ManyToManyField(to='ETF_services.stock'),
        ),
    ]
