# Generated by Django 5.0.6 on 2024-06-20 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETF_services', '0002_firm_availabilitydate_firm_etf_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Fundhouse',
            },
        ),
        migrations.RemoveField(
            model_name='etf',
            name='firm',
        ),
        migrations.RenameField(
            model_name='availabilitydate',
            old_name='firm',
            new_name='fund_house',
        ),
        migrations.RenameField(
            model_name='etf_holdings',
            old_name='firm',
            new_name='fund_house',
        ),
        migrations.AddField(
            model_name='etf',
            name='fund_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Etfs', to='ETF_services.fundhouse'),
        ),
        migrations.DeleteModel(
            name='Firm',
        ),
    ]
